### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by BizCub** [cootshk/GodAppleLimit#1]
Not a mistake, but can you tell me how to make a mod from a datapack. I know that I need to somehow use some code from git modrinth, but I don't know how. Thank you in advance

**Comment by cootshk** [comment]
Include a file called “fabric.mod.json”, and fill it out with the details of your mod. Then you can just compress to a .zip, and rename the zip extension to JAR

Friend me on discord (@cootshk) and I can make one for you.

**Comment by BizCub** [comment]
Thank you very much for the answer. But I already made a mod by clicking the "Package as mod" button
